export const advisors = [
    {
        id: 1,
        name: "Anna Müller",
        email: "anna.mueller@example.com",
        phone: "+49 170 1234567",
        imageUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    },
    {
        id: 2,
        name: "Peter Schmidt",
        email: "peter.schmidt@example.com",
        phone: "+49 170 9876543",
        imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
        id: 3,
        name: "Laura Becker",
        email: "laura.becker@example.com",
        phone: "+49 170 2468102",
        imageUrl: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    {
        id: 4,
        name: "Michael Weber",
        email: "michael.weber@example.com",
        phone: "+49 170 1357924",
        imageUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    },
    {
        id: 5,
        name: "Julia Hoffmann",
        email: "julia.hoffmann@example.com",
        phone: "+49 170 2468013",
        imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    },
    {
        id: 6,
        name: "Thomas Schulz",
        email: "thomas.schulz@example.com",
        phone: "+49 170 1357998",
        imageUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
        id: 7,
        name: "Lisa Wagner",
        email: "lisa.wagner@example.com",
        phone: "+49 170 1357913",
        imageUrl: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    {
        id: 8,
        name: "Stefan Fischer",
        email: "stefan.fischer@example.com",
        phone: "+49 170 1357921",
        imageUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
        id: 9,
        name: "Nina Schmidt",
        email: "nina.schmidt@example.com",
        phone: "+49 170 1357999",
        imageUrl: "https://randomuser.me/api/portraits/women/5.jpg",
    },
    {
        id: 10,
        name: "Jörg Becker",
        email: "joerg.becker@example.com",
        phone: "+49 170 1357925",
        imageUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
        id: 11,
        name: "Markus Richter",
        email: "markus.richter@example.com",
        phone: "+49 170 1357918",
        imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
    },
    {
        id: 12,
        name: "Katrin Schwarz",
        email: "katrin.schwarz@example.com",
        phone: "+49 170 1357916",
        imageUrl: "https://randomuser.me/api/portraits/women/6.jpg",
    },
    {
        id: 13,
        name: "Felix Lange",
        email: "felix.lange@example.com",
        phone: "+49 170 1357917",
        imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
        id: 14,
        name: "Sophie Schneider",
        email: "sophie.schneider@example.com",
        phone: "+49 170 1357915",
        imageUrl: "https://randomuser.me/api/portraits/women/7.jpg",
    },
    {
        id: 15,
        name: "Paul Schmidt",
        email: "paul.schmidt@example.com",
        phone: "+49 170 1357914",
        imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    },
    {
        id: 16,
        name: "Anna Hoffmann",
        email: "anna.hoffmann@example.com",
        phone: "+49 170 1357920",
        imageUrl: "https://randomuser.me/api/portraits/women/8.jpg",
    },
    {
        id: 17,
        name: "Jonas Meier",
        email: "jonas.meier@example.com",
        phone: "+49 170 1357929",
        imageUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    },
    {
        id: 18,
        name: "Clara Krüger",
        email: "clara.krueger@example.com",
        phone: "+49 170 1357930",
        imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
    },
    {
        id: 19,
        name: "Tobias Schröder",
        email: "tobias.schroeder@example.com",
        phone: "+49 170 7890123",
        imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
    },
    {
        id: 20,
        name: "Felix Braun",
        email: "felix.braun@example.com",
        phone: "+49 170 6543210",
        imageUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    },
];
