export const products = [
    {
        id: 1,
        name: "Baugerüst",
        price: 799.99,
        availability: "Auf Lager",
        stock: 50,
        productNumber: "BG-001",
        category: "Baustellengeräte",
        advisorId: 1,  
        rating: 4.7,
        reviewsCount: 25,
        customerGroups: ["Bauunternehmen", "Privatkunden"], 
    },
    {
        id: 2,
        name: "Betonmischer",
        price: 599.99,
        availability: "Begrenzt verfügbar",
        stock: 15,
        productNumber: "BM-002",
        category: "Baumaschinen",
        advisorId: 2,  
        rating: 4.5,
        reviewsCount: 15,
        customerGroups: ["Bauunternehmen"], 
    },
    {
        id: 3,
        name: "Schubkarre",
        price: 89.99,
        availability: "Auf Lager",
        stock: 120,
        productNumber: "SK-003",
        category: "Handwerkzeuge",
        advisorId: 3,  
        rating: 4.8,
        reviewsCount: 20,
        customerGroups: ["Privatkunden", "Gartenbau"], 
    },
    {
        id: 4,
        name: "Schutzhelm",
        price: 19.99,
        availability: "Auf Lager",
        stock: 500,
        productNumber: "SH-004",
        category: "Schutzausrüstung",
        advisorId: 4,  
        rating: 4.3,
        reviewsCount: 10,
        customerGroups: ["Bauunternehmen", "Privatkunden"], 
    },
    {
        id: 5,
        name: "Rüttelplatte",
        price: 1299.99,
        availability: "Begrenzt verfügbar",
        stock: 10,
        productNumber: "RP-005",
        category: "Baumaschinen",
        advisorId: 5,  
        rating: 4.6,
        reviewsCount: 18,
        customerGroups: ["Bauunternehmen"], 
    },
    {
        id: 6,
        name: "Kabeltrommel",
        price: 59.99,
        availability: "Auf Lager",
        stock: 100,
        productNumber: "KT-006",
        category: "Baustellengeräte",
        advisorId: 6,  
        rating: 4.9,
        reviewsCount: 12,
        customerGroups: ["Privatkunden", "Bauunternehmen"], 
    },
    {
        id: 7,
        name: "Leiter",
        price: 79.99,
        availability: "Auf Lager",
        stock: 200,
        productNumber: "LT-007",
        category: "Handwerkzeuge",
        advisorId: 7,  
        rating: 4.4,
        reviewsCount: 22,
        customerGroups: ["Privatkunden", "Bauunternehmen"], 
    },
    {
        id: 8,
        name: "Sicherheitsstiefel",
        price: 99.99,
        availability: "Auf Lager",
        stock: 150,
        productNumber: "SS-008",
        category: "Schutzausrüstung",
        advisorId: 8,  
        rating: 4.2,
        reviewsCount: 15,
        customerGroups: ["Bauunternehmen", "Privatkunden"], 
    },
    {
        id: 9,
        name: "Gerüstbock",
        price: 49.99,
        availability: "Begrenzt verfügbar",
        stock: 40,
        productNumber: "GB-009",
        category: "Baustellengeräte",
        advisorId: 9,  
        rating: 4.8,
        reviewsCount: 30,
        customerGroups: ["Bauunternehmen"], 
    },
    {
        id: 10,
        name: "Werkzeugkasten",
        price: 69.99,
        availability: "Auf Lager",
        stock: 60,
        productNumber: "WK-010",
        category: "Handwerkzeuge",
        advisorId: 10,  
        rating: 4.5,
        reviewsCount: 5,
        customerGroups: ["Privatkunden", "Bauunternehmen"], 
    },
    {
        id: 11,
        name: "Bauzaun",
        price: 149.99,
        availability: "Vorbestellbar",
        stock: 0,
        productNumber: "BZ-011",
        category: "Baustellengeräte",
        advisorId: 11,  
        rating: 4.6,
        reviewsCount: 8,
        customerGroups: ["Bauunternehmen"], 
    },
    {
        id: 12,
        name: "Presslufthammer",
        price: 999.99,
        availability: "Auf Lager",
        stock: 12,
        productNumber: "PH-012",
        category: "Baumaschinen",
        advisorId: 12,  
        rating: 4.4,
        reviewsCount: 12,
        customerGroups: ["Bauunternehmen"], 
    },
    {
        id: 13,
        name: "Warnweste",
        price: 14.99,
        availability: "Auf Lager",
        stock: 500,
        productNumber: "WW-013",
        category: "Schutzausrüstung",
        advisorId: 13,  
        rating: 4.7,
        reviewsCount: 18,
        customerGroups: ["Privatkunden", "Bauunternehmen"], 
    },
    {
        id: 14,
        name: "Schaufel",
        price: 24.99,
        availability: "Auf Lager",
        stock: 300,
        productNumber: "SF-014",
        category: "Handwerkzeuge",
        advisorId: 14,  
        rating: 4.6,
        reviewsCount: 22,
        customerGroups: ["Privatkunden", "Gartenbau"], 
    },
    {
        id: 15,
        name: "Bauhandschuhe",
        price: 12.99,
        availability: "Auf Lager",
        stock: 1000,
        productNumber: "BH-015",
        category: "Schutzausrüstung",
        advisorId: 15,  
        rating: 4.5,
        reviewsCount: 10,
        customerGroups: ["Bauunternehmen", "Privatkunden"], 
    },
    {
        id: 16,
        name: "Wasserwaage",
        price: 19.99,
        availability: "Auf Lager",
        stock: 400,
        productNumber: "WW-016",
        category: "Handwerkzeuge",
        advisorId: 16,  
        rating: 4.8,
        reviewsCount: 30,
        customerGroups: ["Privatkunden", "Bauunternehmen"], 
    },
    {
        id: 17,
        name: "Bolzenschneider",
        price: 49.99,
        availability: "Begrenzt verfügbar",
        stock: 20,
        productNumber: "BS-017",
        category: "Handwerkzeuge",
        advisorId: 17,  
        rating: 4.2,
        reviewsCount: 14,
        customerGroups: ["Bauunternehmen", "Privatkunden"], 
    },
    {
        id: 18,
        name: "Fliesenschneider",
        price: 79.99,
        availability: "Begrenzt verfügbar",
        stock: 15,
        productNumber: "FS-018",
        category: "Baustellengeräte",
        advisorId: 18,  
        rating: 4.6,
        reviewsCount: 20,
        customerGroups: ["Bauunternehmen", "Privatkunden"], 
    },
    {
        id: 19,
        name: "Steinsäge",
        price: 899.99,
        availability: "Vorbestellbar",
        stock: 0,
        productNumber: "SS-019",
        category: "Baumaschinen",
        advisorId: 19,  
        rating: 4.3,
        reviewsCount: 15,
        customerGroups: ["Bauunternehmen"], 
    },
    {
        id: 20,
        name: "Gerüstschutznetz",
        price: 199.99,
        availability: "Auf Lager",
        stock: 80,
        productNumber: "GS-020",
        category: "Baustellengeräte",
        advisorId: 20,  
        rating: 4.1,
        reviewsCount: 10,
        customerGroups: ["Bauunternehmen", "Privatkunden"], 
    },
];
